function showcase(){var X='',eb='" for "gwt:onLoadErrorFn"',cb='" for "gwt:onPropertyErrorFn"',fb='#',Sb='.cache.js',hb='/',Lb='2A96CD3D2A3AC7E3AABA40877578D69A',Mb='85C24E6564433F3C5D1A764CA8F4E5DE',Nb='955C36D89BBA05136482E193DBBAAAF0',Rb=':',Y='::',L='<html><head><\/head><body><\/body><\/html>',_='=',gb='?',Ob='A054B2CF778E2AC2A43A8FD28335DF4D',zb='ActiveXObject',bb='Bad handler "',Pb='C4D5BD8A422DBBF6187512C6A0451557',Ab='ChromeTab.ChromeFrame',Qb='D6A46A3CBE3AF4D862E0B0AFB6997263',Q='DOMContentLoaded',G='DUMMY',ob='android',mb='base',kb='baseUrl',B='begin',tb='blackberry',H='body',A='bootstrap',yb='chromeframe',jb='clear.cache.gif',$='content',Ub='end',Gb='gecko',Hb='gecko1_8',C='gwt.codesvr.showcase=',D='gwt.codesvr=',db='gwt:onLoadErrorFn',ab='gwt:onPropertyErrorFn',Z='gwt:property',T='head',Fb='ie6',Eb='ie8',Db='ie9',I='iframe',ib='img',sb='ipad',qb='iphone',rb='ipod',N='javascript',J='javascript:""',Tb='loadExternalRefs',U='meta',nb='mobile.user.agent',pb='mobilesafari',S='moduleRequested',R='moduleStartup',Cb='msie',V='name',ub='not_mobile',wb='opera',K='position:absolute; width:0; height:0; border:none; left: -1000px; top: -1000px; !important',Bb='safari',M='script',Jb='selectingPermutation',E='showcase',Kb='showcase.devmode.js',lb='showcase.nocache.js',W='showcase::',F='startup',P='undefined',Ib='unknown',vb='user.agent',O='var $wnd = window.parent;',xb='webkit';var n=window;var o=document;q(A,B);function p(){var a=n.location.search;return a.indexOf(C)!=-1||a.indexOf(D)!=-1}
function q(a,b){if(n.__gwtStatsEvent){n.__gwtStatsEvent({moduleName:E,sessionId:n.__gwtStatsSessionId,subSystem:F,evtGroup:a,millis:(new Date).getTime(),type:b})}}
showcase.__sendStats=q;showcase.__moduleName=E;showcase.__errFn=null;showcase.__moduleBase=G;showcase.__softPermutationId=0;showcase.__computePropValue=null;var r=function(){return false};var s=function(){return null};__propertyErrorFunction=null;function t(f){var g;function h(){j();return g}
function i(){j();return g.getElementsByTagName(H)[0]}
function j(){if(g){return}var a=o.createElement(I);a.src=J;a.id=E;a.style.cssText=K;a.tabIndex=-1;o.body.appendChild(a);g=a.contentDocument;if(!g){g=a.contentWindow.document}g.open();g.write(L);g.close();var b=g.getElementsByTagName(H)[0];var c=g.createElement(M);c.language=N;var d=O;c.text=d;b.appendChild(c)}
function k(a){function b(){if(typeof o.readyState==P){return typeof o.body!=P&&o.body!=null}return /loaded|complete/.test(o.readyState)}
var c=false;if(b()){c=true;a()}var d;function e(){if(!c){c=true;a();if(o.removeEventListener){o.removeEventListener(Q,e,false)}if(d){clearInterval(d)}}}
if(o.addEventListener){o.addEventListener(Q,function(){e()},false)}var d=setInterval(function(){if(b()){e()}},50)}
function l(a){var b=i();var c=h().createElement(M);c.language=N;c.text=a;b.appendChild(c);b.removeChild(c)}
showcase.onScriptDownloaded=function(a){k(function(){l(a)})};q(R,S);var m=o.createElement(M);m.src=f;o.getElementsByTagName(T)[0].appendChild(m)}
function u(){var c={};var d;var e;var f=o.getElementsByTagName(U);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(V),k;if(j){j=j.replace(W,X);if(j.indexOf(Y)>=0){continue}if(j==Z){k=i.getAttribute($);if(k){var l,m=k.indexOf(_);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=X}c[j]=l}}else if(j==ab){k=i.getAttribute($);if(k){try{d=eval(k)}catch(a){alert(bb+k+cb)}}}else if(j==db){k=i.getAttribute($);if(k){try{e=eval(k)}catch(a){alert(bb+k+eb)}}}}}s=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;showcase.__errFn=e}
function v(){function e(a){var b=a.lastIndexOf(fb);if(b==-1){b=a.length}var c=a.indexOf(gb);if(c==-1){c=a.length}var d=a.lastIndexOf(hb,Math.min(c,b));return d>=0?a.substring(0,d+1):X}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=o.createElement(ib);b.src=a+jb;a=e(b.src)}return a}
function g(){var a=s(kb);if(a!=null){return a}return X}
function h(){var a=o.getElementsByTagName(M);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(lb)!=-1){return e(a[b].src)}}return X}
function i(){var a=o.getElementsByTagName(mb);if(a.length>0){return a[a.length-1].href}return X}
var j=g();if(j==X){j=h()}if(j==X){j=i()}if(j==X){j=e(o.location.href)}j=f(j);return j}
function w(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return showcase.__moduleBase+a}
function x(){var f=[];var g;function h(a,b){var c=f;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
j[nb]=function(){{var b=function(){var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(ob)!=-1){return pb}if(a.indexOf(qb)!=-1){return pb}if(a.indexOf(rb)!=-1){return pb}if(a.indexOf(sb)!=-1){return pb}if(a.indexOf(tb)!=-1){return ub}return ub}();return b}};i[nb]={mobilesafari:0,not_mobile:1};j[vb]=function(){var c=navigator.userAgent.toLowerCase();var d=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return c.indexOf(wb)!=-1}())return wb;if(function(){return c.indexOf(xb)!=-1||function(){if(c.indexOf(yb)!=-1){return true}if(typeof window[zb]!=P){try{var b=new ActiveXObject(Ab);if(b){b.registerBhoIfNeeded();return true}}catch(a){}}return false}()}())return Bb;if(function(){return c.indexOf(Cb)!=-1&&o.documentMode>=9}())return Db;if(function(){return c.indexOf(Cb)!=-1&&o.documentMode>=8}())return Eb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(c);if(a&&a.length==3)return d(a)>=6000}())return Fb;if(function(){return c.indexOf(Gb)!=-1}())return Hb;return Ib};i[vb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};r=function(a,b){return b in i[a]};showcase.__computePropValue=k;q(A,Jb);if(p()){return w(Kb)}var l;try{h([ub,Bb],Lb);h([ub,Eb],Mb);h([pb,Bb],Nb);h([ub,Db],Ob);h([ub,wb],Pb);h([ub,Hb],Qb);l=f[k(nb)][k(vb)];var m=l.indexOf(Rb);if(m!=-1){g=l.substring(m+1);l=l.substring(0,m)}}catch(a){}showcase.__softPermutationId=g;return w(l+Sb)}
function y(){if(!n.__gwt_stylesLoaded){n.__gwt_stylesLoaded={}}q(Tb,B);q(Tb,Ub)}
u();showcase.__moduleBase=v();var z=x();y();q(A,Ub);t(z)}
showcase();